all: \
	ep01_-_Hello_World/comp.bit \
	ep02_-_Binary_Digits/comp.bit \
	ep03_-_Memory/comp.bit \
	ep04a_-_Clock_Domains/comp.bit \
	ep04_-_Hexadecimal/comp.bit \
	ep05_-_Datapath/comp.bit \
	ep06_-_Load_And_Store/comp.bit \
	ep07_-_Control_Logic/comp.bit \
	ep08_-_ALU/comp.bit \
	ep09_-_Branching/comp.bit \
	ep10_-_Assembler/comp.bit \
	ep11_-_Zero_Page/comp.bit \
	ep12_-_Stack_Pointer/comp.bit \
	ep13_-_More_ALU/comp.bit \
	ep14_-_Registers_X_and_Y/comp.bit \
	ep15_-_Indexed_Addressing/comp.bit \
	ep16_-_Indirect_Addressing/comp.bit \
	ep17_-_Software_Interrupts/comp.bit \
	ep18_-_Hardware_Interrupts/comp.bit \
	ep19_-_C_Runtime/fpga/comp.bit \
	ep20_-_Text_Display/fpga/comp.bit \
	ep21_-_Reading_From_Display_Memory/fpga/comp.bit \
	ep22_-_Memory_Mapped_IO/fpga/comp.bit \
	ep23_-_Interrupt_Controller/fpga/comp.bit \
	ep24_-_Keyboard/fpga/comp.bit \
	ep25_-_Sample_Programs/fpga/comp.bit \
	ep26_-_Ethernet_PHY/fpga/comp.bit \
	ep27_-_Rx_DMA/fpga/comp.bit \
	ep28_-_Tx_DMA/fpga/comp.bit \
	ep29_-_Protocol_Stack/fpga/comp.bit

ep01_-_Hello_World/comp.bit :
	make -C ep01_-_Hello_World

ep02_-_Binary_Digits/comp.bit :
	make -C ep02_-_Binary_Digits

ep03_-_Memory/comp.bit :
	make -C ep03_-_Memory

ep04_-_Hexadecimal/comp.bit :
	make -C ep04_-_Hexadecimal

ep04a_-_Clock_Domains/comp.bit :
	make -C ep04a_-_Clock_Domains

ep05_-_Datapath/comp.bit :
	make -C ep05_-_Datapath

ep06_-_Load_And_Store/comp.bit :
	make -C ep06_-_Load_And_Store

ep07_-_Control_Logic/comp.bit :
	make -C ep07_-_Control_Logic

ep08_-_ALU/comp.bit :
	make -C ep08_-_ALU

ep09_-_Branching/comp.bit :
	make -C ep09_-_Branching

ep10_-_Assembler/comp.bit :
	make -C ep10_-_Assembler

ep11_-_Zero_Page/comp.bit :
	make -C ep11_-_Zero_Page

ep12_-_Stack_Pointer/comp.bit :
	make -C ep12_-_Stack_Pointer

ep13_-_More_ALU/comp.bit :
	make -C ep13_-_More_ALU

ep14_-_Registers_X_and_Y/comp.bit :
	make -C ep14_-_Registers_X_and_Y

ep15_-_Indexed_Addressing/comp.bit :
	make -C ep15_-_Indexed_Addressing

ep16_-_Indirect_Addressing/comp.bit :
	make -C ep16_-_Indirect_Addressing

ep17_-_Software_Interrupts/comp.bit :
	make -C ep17_-_Software_Interrupts

ep18_-_Hardware_Interrupts/comp.bit :
	make -C ep18_-_Hardware_Interrupts

ep19_-_C_Runtime/fpga/comp.bit :
	make -C ep19_-_C_Runtime

ep20_-_Text_Display/fpga/comp.bit :
	make -C ep20_-_Text_Display

ep21_-_Reading_From_Display_Memory/fpga/comp.bit :
	make -C ep21_-_Reading_From_Display_Memory

ep22_-_Memory_Mapped_IO/fpga/comp.bit :
	make -C ep22_-_Memory_Mapped_IO

ep23_-_Interrupt_Controller/fpga/comp.bit :
	make -C ep23_-_Interrupt_Controller

ep24_-_Keyboard/fpga/comp.bit :
	make -C ep24_-_Keyboard

ep25_-_Sample_Programs/fpga/comp.bit :
	make -C ep25_-_Sample_Programs

ep26_-_Ethernet_PHY/fpga/comp.bit :
	make -C ep26_-_Ethernet_PHY

ep27_-_Rx_DMA/fpga/comp.bit :
	make -C ep27_-_Rx_DMA

ep28_-_Tx_DMA/fpga/comp.bit :
	make -C ep28_-_Tx_DMA

ep29_-_Protocol_Stack/fpga/comp.bit :
	make -C ep29_-_Protocol_Stack

