#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "memorymap.h"
#include "ethernet.h"

// This variable is only used during simulation, to test the arbitration
// between CPU and Ethernet while writing to memory.
uint8_t dummy_counter;

// Start of receive buffer.
uint8_t *pBuf;

// Current read pointer of the CPU
uint8_t *rdPtr;

// Length of current frame
uint16_t frmLen;

void main(void)
{
   // Allocate receive buffer. This will never be free'd.
   // Using malloc (rather than a globally allocated array) avoids a call to
   // memset generated by the compiler, thereby reducing simulation time.
   // The size must be at least an entire Ethernet frame including 2-byte header.
   pBuf  = (uint8_t *) malloc(1516);

   // Verify that Rx DMA is disabled from start.
   assert(MEMIO_CONFIG->ethRxdmaEnable == 0);

   // Configure Ethernet Rx DMA. May only be done while Rx DMA is disabled.
   MEMIO_CONFIG->ethRxdmaPtr = (uint16_t) pBuf;

   // Wait for data to be received, and print to the screen
   while (1)
   {
      // Indicate to Rx DMA that we are ready to receive a frame.
      MEMIO_CONFIG->ethRxdmaEnable = 1;

      // Wait until an ethernet frame has been received
      while (MEMIO_CONFIG->ethRxdmaEnable == 1)
      {
         dummy_counter += 1;   // This generates a write to the main memory.
      }

      // Calculate length of frame
      frmLen = *((uint16_t *)pBuf);  // Read as little-endian.

      processFrame(pBuf+2, frmLen-2);
   }

} // end of main

