-- file: clk_rst.vhd (originally clk_wiz_0_clk_wiz.vhd)
-- 
-- (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
------------------------------------------------------------------------------
-- Comments
------------------------------------------------------------------------------
-- This file was originally generated by the Xilinx Clocking Wizard (as
-- clk_wiz_0_clk_wiz.vhd), and has since been modified by hand, i.e. the
-- Ethernet clock has been removed, the frequencies have been changed, and the
-- reset generation has been added.
--
-- The MMCM divides the 100 MHz input clock by G_VCO_DIVIDE and multiplies it
-- by G_VCO_MULT, which gives the VCO frequency, and generates the following
-- output clocks from the VCO:
--
--   Output clock   Output    Divider         Freq (MHz)
--   vga_clk        CLKOUT1   G_VGA_DIVIDE    VCO/G_VGA_DIVIDE
--   main_clk       CLKOUT0   G_MAIN_DIVIDE   VCO/G_MAIN_DIVIDE
--
-- All of these are set by the top level module:
-- * Nexys 4 DDR: The VCO is 100 MHz * 12 = 1200 MHz (the maximum for speed
--   grade -1). The VGA clock is 1200/48 = 25 MHz (640x480), and the main clock
--   is 1200/8 = 150 MHz.
-- * MEGA65: The VCO is 1200 MHz too (speed grade -2 allows up to 1440 MHz).
--   The VGA clock is 1200/30 = 40 MHz (800x600), and the main clock is
--   1200/6.375 = 188.235 MHz.
-- The main clock uses CLKOUT0, because it is the only output with a
-- fractional divider (in steps of 0.125).
--
-- Input clock: clk_i, 100.000 MHz.
--
-- Each output clock has a corresponding reset, which is synchronous to that
-- clock. The design is held in reset while the reset button is pressed
-- (rstn_i low), and while the MMCM is not locked. This signal is
-- asynchronous, so it is first synchronized to each clock domain (two
-- registers), and the reset is then stretched to eight clock cycles after it
-- is released.

library ieee;
use ieee.std_logic_1164.all;

library unisim;
use unisim.vcomponents.all;

entity clk_rst is
   generic (
      G_VCO_DIVIDE  : integer;     -- The VCO is 100 MHz / G_VCO_DIVIDE * G_VCO_MULT
      G_VCO_MULT    : real;
      G_MAIN_DIVIDE : real;        -- The main clock is VCO / G_MAIN_DIVIDE
      G_VGA_DIVIDE  : integer      -- The VGA clock is VCO / G_VGA_DIVIDE
   );
   port (
      clk_i      : in  std_logic;  -- 100 MHz
      rstn_i     : in  std_logic;  -- Asynchronous, active low

      main_clk_o : out std_logic;  -- VCO / G_MAIN_DIVIDE
      main_rst_o : out std_logic;  -- Synchronous to main_clk_o

      vga_clk_o  : out std_logic;  -- VCO / G_VGA_DIVIDE
      vga_rst_o  : out std_logic   -- Synchronous to vga_clk_o
   );
end clk_rst;

architecture xilinx of clk_rst is

   signal clkfb_mmcm     : std_logic;
   signal clkfb          : std_logic;
   signal main_clk_mmcm  : std_logic;
   signal vga_clk_mmcm   : std_logic;
   signal locked         : std_logic;
   signal rstn           : std_logic;

   signal main_clk       : std_logic;
   signal main_rstn_sync : std_logic_vector(1 downto 0) := "00";
   signal main_rst_delay : std_logic_vector(7 downto 0) := X"FF";

   signal vga_clk        : std_logic;
   signal vga_rstn_sync  : std_logic_vector(1 downto 0) := "00";
   signal vga_rst_delay  : std_logic_vector(7 downto 0) := X"FF";

   -- The registers of the reset synchronizers
   attribute ASYNC_REG : string;
   attribute ASYNC_REG of main_rstn_sync : signal is "TRUE";
   attribute ASYNC_REG of vga_rstn_sync  : signal is "TRUE";

begin

   --------------------------------------------------
   -- Instantiate the MMCM
   --------------------------------------------------

   -- Unused outputs are left unconnected, and unused inputs are tied off.
   mmcm_adv_inst : MMCME2_ADV
      generic map (
         BANDWIDTH            => "OPTIMIZED",
         CLKOUT4_CASCADE      => FALSE,
         COMPENSATION         => "ZHOLD",
         STARTUP_WAIT         => FALSE,
         DIVCLK_DIVIDE        => G_VCO_DIVIDE,
         CLKFBOUT_MULT_F      => G_VCO_MULT,
         CLKFBOUT_PHASE       => 0.000,
         CLKFBOUT_USE_FINE_PS => FALSE,
         CLKOUT0_DIVIDE_F     => G_MAIN_DIVIDE, -- MAIN
         CLKOUT0_PHASE        => 0.000,
         CLKOUT0_DUTY_CYCLE   => 0.500,
         CLKOUT0_USE_FINE_PS  => FALSE,
         CLKOUT1_DIVIDE       => G_VGA_DIVIDE,  -- VGA
         CLKOUT1_PHASE        => 0.000,
         CLKOUT1_DUTY_CYCLE   => 0.500,
         CLKOUT1_USE_FINE_PS  => FALSE,
         CLKIN1_PERIOD        => 10.0,
         REF_JITTER1          => 0.010
      )
      port map (
         CLKFBOUT => clkfb_mmcm,
         CLKOUT0  => main_clk_mmcm,
         CLKOUT1  => vga_clk_mmcm,
         CLKFBIN  => clkfb,
         CLKIN1   => clk_i,
         CLKIN2   => '0',
         CLKINSEL => '1',               -- Select CLKIN1
         DADDR    => (others => '0'),
         DCLK     => '0',
         DEN      => '0',
         DI       => (others => '0'),
         DWE      => '0',
         PSCLK    => '0',
         PSEN     => '0',
         PSINCDEC => '0',
         LOCKED   => locked,
         PWRDWN   => '0',
         RST      => '0'
      ); -- mmcm_adv_inst

   clkfb_buf : BUFG
      port map (
         I => clkfb_mmcm,
         O => clkfb
      ); -- clkfb_buf

   main_clk_buf : BUFG
      port map (
         I => main_clk_mmcm,
         O => main_clk
      ); -- main_clk_buf

   vga_clk_buf : BUFG
      port map (
         I => vga_clk_mmcm,
         O => vga_clk
      ); -- vga_clk_buf


   --------------------------------------------------
   -- Generate reset signals
   --------------------------------------------------

   -- The design is held in reset while the reset button is pressed, and while
   -- the MMCM is not locked. This signal is asynchronous, so it is first
   -- synchronized to each clock domain (two registers), and the reset is then
   -- stretched to eight clock cycles after it is released.
   rstn <= rstn_i and locked;

   p_main_rst : process (main_clk)
   begin
      if rising_edge(main_clk) then
         main_rstn_sync <= main_rstn_sync(0) & rstn;

         main_rst_delay <= main_rst_delay(6 downto 0) & "0";
         main_rst_o <= main_rst_delay(7);

         if main_rstn_sync(1) = '0' then
            main_rst_delay <= X"FF";
         end if;
      end if;
   end process p_main_rst;

   p_vga_rst : process (vga_clk)
   begin
      if rising_edge(vga_clk) then
         vga_rstn_sync <= vga_rstn_sync(0) & rstn;

         vga_rst_delay <= vga_rst_delay(6 downto 0) & "0";
         vga_rst_o <= vga_rst_delay(7);

         if vga_rstn_sync(1) = '0' then
            vga_rst_delay <= X"FF";
         end if;
      end if;
   end process p_vga_rst;

   main_clk_o <= main_clk;
   vga_clk_o  <= vga_clk;

end xilinx;
