#!/usr/bin/env python3
# Generates src/vga/font_pkg.vhd, the font of the frame rate overlay (see
# src/vga/overlay.vhd), from the Spleen 16x32 font. Only the digits 0 to 9 are
# used. Spleen is licensed under the BSD 2-Clause license, see LICENSE.spleen.
#
# Usage (from the mandelbrot folder):
#   git clone https://github.com/fcambus/spleen
#   python3 font/gen_font_pkg.py spleen/spleen-16x32.bdf > src/vga/font_pkg.vhd

import sys

WIDTH  = 16
HEIGHT = 32


def load_bdf(filename):
    """Returns a dictionary from code point to the rows of the glyph."""
    glyphs  = {}
    version = None
    code    = None
    rows   = None
    for line in open(filename):
        words = line.split()
        if not words:
            continue
        if words[0] == 'FONT_VERSION':
            version = words[1].strip('"')
        elif words[0] == 'FONTBOUNDINGBOX':
            assert words[1:3] == [str(WIDTH), str(HEIGHT)], 'Wrong font size'
        elif words[0] == 'ENCODING':
            code = int(words[1])
        elif words[0] == 'BBX':
            # All glyphs of Spleen fill the whole cell
            assert words[1:3] == [str(WIDTH), str(HEIGHT)], 'Wrong glyph size'
        elif words[0] == 'BITMAP':
            rows = []
        elif words[0] == 'ENDCHAR':
            glyphs[code] = rows
            rows = None
        elif rows is not None:
            rows.append(int(words[0], 16))
    return version, glyphs


def main():
    version, glyphs = load_bdf(sys.argv[1])

    print('-- This file is generated by font/gen_font_pkg.py. Do not edit.')
    print('--')
    print('-- The digits 0 to 9 of the Spleen 16x32 font, version %s, from' % version)
    print('-- https://github.com/fcambus/spleen (spleen-16x32.bdf):')
    print('--')
    for line in open(sys.argv[0].replace('gen_font_pkg.py', 'LICENSE.spleen')):
        print(('-- ' + line.rstrip()).rstrip())
    print('--')
    print('-- C_FONT holds %d rows of %d pixels for each digit, the top row first. The' % (HEIGHT, WIDTH))
    print('-- row r of the digit d is at index 32*d + r. The leftmost pixel is bit 15.')
    print('-- Indices above the digit 9 are not used, and are zero.')
    print('')
    print('library ieee;')
    print('use ieee.std_logic_1164.all;')
    print('')
    print('package font_pkg is')
    print('')
    print('   type font_t is array (0 to 511) of std_logic_vector(%d downto 0);' % (WIDTH-1))
    print('')
    print('   constant C_FONT : font_t := (')
    for d in range(10):
        rows = glyphs[ord('0') + d]
        for r, value in enumerate(rows):
            picture = ''.join('#' if value >> (WIDTH-1-i) & 1 else '.' for i in range(WIDTH))
            print('      %3d => "%s",  -- %s' % (HEIGHT*d + r, format(value, '0%db' % WIDTH), picture))
    print('      others => (others => \'0\'));')
    print('')
    print('end package font_pkg;')
    print('')


if __name__ == '__main__':
    main()
