set_property LOC H17 [get_ports led[0]]
set_property LOC K15 [get_ports led[1]]
set_property LOC J13 [get_ports led[2]]
set_property LOC N14 [get_ports led[3]]
set_property LOC R18 [get_ports led[4]]
set_property LOC V17 [get_ports led[5]]
set_property LOC U17 [get_ports led[6]]
set_property LOC U16 [get_ports led[7]]
set_property LOC V16 [get_ports led[8]]
set_property LOC T15 [get_ports led[9]]
set_property LOC U14 [get_ports led[10]]
set_property LOC T16 [get_ports led[11]]

set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports led[13]]
set_property IOSTANDARD LVCMOS33 [get_ports led[14]]
set_property IOSTANDARD LVCMOS33 [get_ports led[15]]

set_property LOC J15 [get_ports sw[0]]
set_property LOC L16 [get_ports sw[1]]
set_property LOC M13 [get_ports sw[2]]
set_property LOC R15 [get_ports sw[3]]

set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]

set_property LOC E3 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]

