# Name of top level module
TOP = queens_top

# List of sources files
SRC  = src/$(TOP).vhd
SRC += src/bitmap_pkg.vhd
SRC += src/queens.vhd
SRC += src/counter.vhd
SRC += src/disp_queens.vhd
SRC += src/vga_controller_640_60.vhd
SRC += src/clk.vhd
SRC += src/seg.vhd
SRC += src/int2seg.vhd
SRC += src/digit.vhd

stoptime = --stop-time=1000us

include ../xilinx.mk


