# Name of top level module
TOP = queens_top

# List of sources files
SRC  = src/$(TOP).vhd
SRC += bitmap_pkg.vhd
SRC += queens.vhd
SRC += counter.vhd
SRC += disp_queens.vhd
SRC += vga_controller_640_60.vhd
SRC += clk.vhd
SRC += seg.vhd
SRC += int2seg.vhd
SRC += digit.vhd

stoptime = --stop-time=1000us

include ../xilinx.mk


