# Name of top level module
TOP = alu_module

# List of sources files
SRC  = $(TOP).vhd
SRC += add.vhd
SRC += cmp.vhd
SRC += boole.vhd
SRC += shift.vhd
TB_SRC = alu_module_tb.vhd
wavesave = alu_module_tb.gtkw

stoptime = --stop-time=5ms

include ../../../../xilinx.mk


