# Name of top level module
TOP = beta

# List of sources files
SRC  = src/$(TOP).vhd
SRC += src/vga_ctrl.vhd
SRC += src/clk_wiz_0.vhd
SRC += src/clk_wiz_0_clk_wiz.vhd

stoptime = --stop-time=5us

include ../xilinx.mk


