# Name of top level module
TOP = beta

# List of sources files
SRC  = src/$(TOP).vhd
SRC += src/vga/vga_module.vhd
SRC += src/vga/clk_wiz_0.vhd
SRC += src/vga/clk_wiz_0_clk_wiz.vhd
SRC += src/vga/vga_ctrl.vhd
SRC += src/vga/vga_bitmap_pkg.vhd
SRC += src/vga/vga_disp.vhd
SRC += src/cpu/cpu_module.vhd

stoptime = --stop-time=5ms

include ../xilinx.mk


