#include <stdint.h>
#include <stdlib.h>
#include <conio.h>
#include "memorymap.h"

#define BUF_SIZE 8000

#define RD_BUF(ptr) ((ptr) < pBufEnd ? *(ptr) : *((ptr)-BUF_SIZE))
//#define ADD_PTR(ptr, add) (ptr+add < pBufEnd ? ptr+add : ptr+add-BUF_SIZE)

void putx8(uint8_t x)
{
   static const char hex[16] = "0123456789ABCDEF";
   cputc(hex[(x>>4) & 0x0F]);
   cputc(hex[(x>>0) & 0x0F]);
}

void putx16(uint16_t x)
{
   putx8((x>>8) & 0xFF);
   putx8((x>>0) & 0xFF);
}

void main(void)
{
   uint8_t dummy_counter = 0;

   // Allocate receive buffer. This will never be free'd.
   // Using malloc avoids a call to memset generated by the compiler.
   // This reduces simulation time.
   uint8_t *pBuf = (uint8_t *) malloc(BUF_SIZE);  // Fairly small buffer to test wrap-around.
   uint8_t *pBufEnd = pBuf + BUF_SIZE;            // First byte after the buffer.

   // Configure Ethernet DMA
   MEMIO_CONFIG->ethEnable = 0;  // DMA must be disabled during configuration.
   MEMIO_CONFIG->ethStart  = (uint16_t) pBuf;
   MEMIO_CONFIG->ethEnd    = (uint16_t) pBuf + BUF_SIZE;
   MEMIO_CONFIG->ethRdPtr  = MEMIO_CONFIG->ethStart;
   MEMIO_CONFIG->ethEnable = 1;
   
   gotoxy(0, 0);

   // Wait for data to be received, and print to the screen
   while (1)
   {
      uint8_t *pktPtr;
      uint8_t *pktEndPtr;
      uint16_t pktLen;
      uint16_t typeLen;
      uint8_t  i;

      dummy_counter += 1;   // This generates a write to the main memory.
      if (MEMIO_CONFIG->ethRdPtr == MEMIO_STATUS->ethWrPtr)
         continue;   // Go back and wait for data

      pktPtr  = (uint8_t *)(MEMIO_CONFIG->ethRdPtr);
      pktEndPtr = (uint8_t *)(MEMIO_STATUS->ethWrPtr);
      pktLen  = RD_BUF(pktPtr+1) << 8 + RD_BUF(pktPtr);     // Little-endian
      typeLen = RD_BUF(pktPtr+14) << 8 + RD_BUF(pktPtr+15); // Big-endian

      putx16((uint16_t)pktPtr);
      cputs("-");
      putx16((uint16_t)pktEndPtr);
      cputs(":");

      for (i=0; i<16; ++i)
      {
         putx8(RD_BUF(pktPtr+i));
      }
      cputs("\n\r");

      MEMIO_CONFIG->ethRdPtr = MEMIO_STATUS->ethWrPtr;
   }

} // end of main

